addSbtPlugin("io.github.davidmweber" % "flyway-sbt" % "6.2.3")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")
addSbtPlugin("au.com.onegeek" %% "sbt-dotenv" % "2.1.146")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.1")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
